# Generated by Django 4.2.5 on 2023-10-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0007_profiles_delete_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Ônibus', 'verbose_name_plural': 'Ônibus'},
        ),
        migrations.AlterModelOptions(
            name='busroute',
            options={'verbose_name': 'Rota', 'verbose_name_plural': 'Rotas'},
        ),
        migrations.AlterModelOptions(
            name='bustype',
            options={'verbose_name': 'Tipo de Ônibus', 'verbose_name_plural': 'Tipos de Ônibus'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localidade', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterField(
            model_name='profiles',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
