# Generated by Django 4.2.5 on 2023-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0008_alter_bus_options_alter_busroute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
