# Generated by Django 4.2.5 on 2023-10-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0009_location_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
