# Generated by Django 4.2.5 on 2023-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0010_remove_location_image_url_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/locations/'),
        ),
    ]
