# Generated by Django 4.2.5 on 2023-10-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0012_busschedule'),
        ('uberdeonibusapp', '0012_busschedules'),
    ]

    operations = [
    ]
