# Generated by Django 4.2.5 on 2023-10-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0013_merge_0012_busschedule_0012_busschedules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busschedule',
            options={'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
    ]
