# Generated by Django 4.2.5 on 2023-11-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0020_busroute_preco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusSchedules',
        ),
    ]
