# Generated by Django 4.2.5 on 2023-11-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0021_delete_busschedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poltrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPoltronas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberdeonibusapp.busschedule')),
                ('poltronas', models.ManyToManyField(to='uberdeonibusapp.poltrona')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberdeonibusapp.busroute')),
            ],
        ),
    ]
