# Generated by Django 4.2.5 on 2023-11-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0022_poltrona_listapoltronas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poltrona',
            options={'verbose_name': 'Poltrona'},
        ),
        migrations.AddField(
            model_name='busschedule',
            name='poltronas',
            field=models.ManyToManyField(to='uberdeonibusapp.poltrona'),
        ),
        migrations.AddField(
            model_name='poltrona',
            name='ocupada',
            field=models.BooleanField(blank=True, null=True, verbose_name='False'),
        ),
        migrations.AddField(
            model_name='poltrona',
            name='passageiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uberdeonibusapp.customuser'),
        ),
        migrations.DeleteModel(
            name='ListaPoltronas',
        ),
    ]
