# Generated by Django 4.2.5 on 2023-11-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0023_alter_poltrona_options_busschedule_poltronas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poltrona',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uberdeonibusapp.busroute'),
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='poltronas',
        ),
        migrations.AlterField(
            model_name='poltrona',
            name='ocupada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ocupada'),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='poltronas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uberdeonibusapp.poltrona'),
        ),
    ]
