# Generated by Django 4.2.5 on 2023-11-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0026_remove_busschedule_schedule_busschedule_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busschedule',
            old_name='time',
            new_name='hora',
        ),
    ]
