# Generated by Django 4.2.5 on 2023-11-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0027_rename_time_busschedule_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusSchedule',
        ),
    ]
