# Generated by Django 4.2.5 on 2023-11-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0029_busschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busschedule',
            name='route',
        ),
        migrations.RemoveField(
            model_name='poltrona',
            name='passageiro',
        ),
        migrations.RemoveField(
            model_name='poltrona',
            name='route',
        ),
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.DeleteModel(
            name='BusSchedule',
        ),
        migrations.DeleteModel(
            name='Poltrona',
        ),
    ]
