# Generated by Django 4.2.5 on 2023-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0031_busroute_poltrona_busschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poltrona',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
