# Generated by Django 4.2.5 on 2023-12-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0020_auto_20231118_1735'),
        ('uberdeonibusapp', '0033_poltrona_horario'),
    ]

    operations = [
    ]
