# Generated by Django 4.2.5 on 2023-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberdeonibusapp', '0035_remove_busroute_schedule_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poltrona',
            name='nome_passageiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
